version: 0.2

run-as: root

env:
  parameter-store:
    DB_NAME: "/aadesh/DB_Name"
    DB_USER: "/aadesh/DB_User"
    DB_PASSWORD: "/aadesh/DB_Password"
    DB_HOST: "/aadesh/DB_Host"

phases:
  install:
    commands:
      - apt update -y
      - apt install nginx php php-fpm -y
  pre_build:
    commands:
      - sed -i 's/database_name_here/'$DB_NAME'/' wp-config.php
      - sed -i 's/username_here/'$DB_USER'/' wp-config.php
      - sed -i 's/password_here/'$DB_PASSWORD'/' wp-config.php
      - sed -i 's/localhost/'$DB_HOST'/' wp-config.php
  build:
    commands:
      - grep -Fq "aadesh" wp-config.php
artifacts:
  files:
    - '**/*'
